/*
 * Magic Carousel v1.2
 *
 * Copyright 2014-2019 LambertGroup
 *
 */


 (function(d){function E(a,b,c){c=b.elementsHorizontalSpacing/(b.contentHolderUnitOrigWidth+2*b.border)*c.aspectOrig;var d=a*(b.contentHolderUnitOrigHeight+2*b.border)/(b.origWidth/b.width);b=2*b.elementsVerticalSpacing/(b.origWidth/b.width);var g=0;for(i=1;i<=a;i++)g+=i;return c*(d-b*g)}function K(a,b){b.responsive&&(newCss="",-1!=a.css("font-size").lastIndexOf("px")?(fontSize=a.css("font-size").substr(0,a.css("font-size").lastIndexOf("px")),newCss+="font-size:"+fontSize/(b.origWidth/b.width)+"px;"):
 -1!=a.css("font-size").lastIndexOf("em")&&(fontSize=a.css("font-size").substr(0,a.css("font-size").lastIndexOf("em")),newCss+="font-size:"+fontSize/(b.origWidth/b.width)+"em;"),-1!=a.css("line-height").lastIndexOf("px")?(lineHeight=a.css("line-height").substr(0,a.css("line-height").lastIndexOf("px")),newCss+="line-height:"+lineHeight/(b.origWidth/b.width)+"px;"):-1!=a.css("line-height").lastIndexOf("em")&&(lineHeight=a.css("line-height").substr(0,a.css("line-height").lastIndexOf("em")),newCss+="line-height:"+
 lineHeight/(b.origWidth/b.width)+"em;"),a.wrapInner('<div class="newFS" style="'+newCss+'" />'))}function I(a,b){nowx=(new Date).getTime();a.mouseOverBanner||a.effectIsRunning||!b.showCircleTimer||a.isPrettyPhoto||(a.ctx.clearRect(0,0,a.canvas.width,a.canvas.height),a.ctx.beginPath(),a.ctx.globalAlpha=b.behindCircleAlpha/100,a.ctx.arc(b.circleRadius+2*b.circleLineWidth,b.circleRadius+2*b.circleLineWidth,b.circleRadius,0,2*Math.PI,!1),a.ctx.lineWidth=b.circleLineWidth+2,a.ctx.strokeStyle=b.behindCircleColor,
 a.ctx.stroke(),a.ctx.beginPath(),a.ctx.globalAlpha=b.circleAlpha/100,a.ctx.arc(b.circleRadius+2*b.circleLineWidth,b.circleRadius+2*b.circleLineWidth,b.circleRadius,0,(a.timeElapsed+nowx-a.arcInitialTime)/1E3*2/b.autoPlay*Math.PI,!1),a.ctx.lineWidth=b.circleLineWidth,a.ctx.strokeStyle=b.circleColor,a.ctx.stroke())}function B(a,b,c,x,g,l,n,y,f){b.showCircleTimer&&d(".mycanvas",l).css({display:"none"});d(x[c.current_img_no]).removeClass("bottomNavButtonON");c.current_img_no=F(c.current_img_no,a,n);c.curIcon=
 "empty.png";d(g[c.current_img_no]).attr("data-link")?c.curIcon="link.png":d(g[c.current_img_no]).attr("data-large-image")?c.curIcon="image.png":d(g[c.current_img_no]).attr("data-video-youtube")||d(g[c.current_img_no]).attr("data-video-vimeo")||d(g[c.current_img_no]).attr("data-video-selfhosted")?c.curIcon="video.png":d(g[c.current_img_no]).attr("data-audio")&&(c.curIcon="audio.png");display_val="block";"empty.png"==c.curIcon&&(display_val="none");y.css({background:"url("+b.absUrl+"skins/"+b.skin+
 "/"+c.curIcon+")",display:display_val});d(x[c.current_img_no]).addClass("bottomNavButtonON");c.currentZ_index=100;c.currentImg=d("#contentHolderUnit_"+c.current_img_no,l);var h=parseInt(b.contentHolderUnitOrigWidth/(b.origWidth/b.width),10);var k=parseInt(b.contentHolderUnitOrigHeight/(b.origWidth/b.width),10);var p=parseInt((b.width-(b.contentHolderUnitOrigWidth+2*b.border)/(b.origWidth/b.width))/2,10);var q=parseInt(b.height-(b.contentHolderUnitOrigHeight+2*b.border)/(b.origWidth/b.width)-b.verticalAdjustment/
 (b.origWidth/b.width),10);D(c.currentImg,p,q,h,k,1,!1,a,c,b,f,g,n,y,x,l);u=c.current_img_no;for(m=1;m<=Math.floor(b.numberOfVisibleItems/2);m++)c.currentZ_index--,u=F(u,-1,n),c.currentImg=d("#contentHolderUnit_"+u,l),c.currentImg.css("z-index",c.currentZ_index),m==Math.floor(b.numberOfVisibleItems/2)&&(1===a?(last_aux_img_no=F(u,-1,n),last_currentImg=d("#contentHolderUnit_"+last_aux_img_no,l),k=parseInt(b.contentHolderUnitOrigHeight/(b.origWidth/b.width)-2*(m+1)*b.elementsVerticalSpacing/(b.origWidth/
 b.width),10),h=parseInt(k*c.aspectOrig,10),p=parseInt((b.width-(b.contentHolderUnitOrigWidth+2*b.border)/(b.origWidth/b.width))/2-E(m+1,b,c),10),q=parseInt(b.height-(b.contentHolderUnitOrigHeight+2*b.border)/(b.origWidth/b.width)-b.verticalAdjustment/(b.origWidth/b.width)+(m+1)*b.elementsVerticalSpacing/(b.origWidth/b.width),10),D(last_currentImg,p,q,h,k,0,!1,a,c,b,g,n,x,l)):(k=parseInt(b.contentHolderUnitOrigHeight/(b.origWidth/b.width)-2*(m+1)*b.elementsVerticalSpacing/(b.origWidth/b.width),10),
 parseInt(k*c.aspectOrig,10),H(c.currentImg,m+1,b,c),p=parseInt((b.width-(b.contentHolderUnitOrigWidth+2*b.border)/(b.origWidth/b.width))/2-E(m+1,b,c),10),q=parseInt(b.height-(b.contentHolderUnitOrigHeight+2*b.border)/(b.origWidth/b.width)-b.verticalAdjustment/(b.origWidth/b.width)+(m+1)*b.elementsVerticalSpacing/(b.origWidth/b.width),10),c.currentImg.css({left:p+"px",top:q+"px",opacity:0}))),c.currentImg.css("display","block"),k=parseInt(b.contentHolderUnitOrigHeight/(b.origWidth/b.width)-2*m*b.elementsVerticalSpacing/
 (b.origWidth/b.width),10),h=parseInt(k*c.aspectOrig,10),p=parseInt((b.width-(b.contentHolderUnitOrigWidth+2*b.border)/(b.origWidth/b.width))/2-E(m,b,c),10),q=parseInt(b.height-(b.contentHolderUnitOrigHeight+2*b.border)/(b.origWidth/b.width)-b.verticalAdjustment/(b.origWidth/b.width)+m*b.elementsVerticalSpacing/(b.origWidth/b.width),10),D(c.currentImg,p,q,h,k,1,!1,a,c,b,g,n,x,l);var u=c.current_img_no;for(m=1;m<=Math.floor(b.numberOfVisibleItems/2);m++)c.currentZ_index--,u=F(u,1,n),c.currentImg=d("#contentHolderUnit_"+
 u,l),c.currentImg.css("z-index",c.currentZ_index),m==Math.floor(b.numberOfVisibleItems/2)&&(1===a?(H(c.currentImg,m+1,b,c),c.currentImg.css({left:parseInt((b.width-(b.contentHolderUnitOrigWidth+2*b.border)/(b.origWidth/b.width))/2+((b.contentHolderUnitOrigWidth+2*b.border)/(b.origWidth/b.width)+E(m+1,b,c)-c.currentImg.width()),10)+"px",top:parseInt(b.height-(b.contentHolderUnitOrigHeight+2*b.border)/(b.origWidth/b.width)-b.verticalAdjustment/(b.origWidth/b.width)+(m+1)*b.elementsVerticalSpacing/(b.origWidth/
 b.width),10)+"px",opacity:0})):(last_aux_img_no=F(u,1,n),last_currentImg=d("#contentHolderUnit_"+last_aux_img_no,l),k=parseInt(b.contentHolderUnitOrigHeight/(b.origWidth/b.width)-2*(m+1)*b.elementsVerticalSpacing/(b.origWidth/b.width),10),h=parseInt(k*c.aspectOrig,10),p=parseInt((b.width-(b.contentHolderUnitOrigWidth+2*b.border)/(b.origWidth/b.width))/2+((b.contentHolderUnitOrigWidth+2*b.border)/(b.origWidth/b.width)+E(m+1,b,c)-h),10),q=parseInt(b.height-(b.contentHolderUnitOrigHeight+2*b.border)/
 (b.origWidth/b.width)-b.verticalAdjustment/(b.origWidth/b.width)+(m+1)*b.elementsVerticalSpacing/(b.origWidth/b.width),10),D(last_currentImg,p,q,h,k,0,!1,a,c,b,g,n,x,l))),c.currentImg.css("display","block"),k=parseInt(b.contentHolderUnitOrigHeight/(b.origWidth/b.width)-2*m*b.elementsVerticalSpacing/(b.origWidth/b.width),10),h=parseInt(k*c.aspectOrig,10),p=parseInt((b.width-(b.contentHolderUnitOrigWidth+2*b.border)/(b.origWidth/b.width))/2+((b.contentHolderUnitOrigWidth+2*b.border)/(b.origWidth/b.width)+
 E(m,b,c)-(h+2*b.border)),10)+1,q=parseInt(b.height-(b.contentHolderUnitOrigHeight+2*b.border)/(b.origWidth/b.width)-b.verticalAdjustment/(b.origWidth/b.width)+m*b.elementsVerticalSpacing/(b.origWidth/b.width),10),m==Math.floor(b.numberOfVisibleItems/2)?D(c.currentImg,p,q,h,k,1,!0,a,c,b,f,g,n,y,x,l):D(c.currentImg,p,q,h,k,1,!1,a,c,b,f,g,n,y,x,l)}function H(a,b,c,d){b=parseInt(c.contentHolderUnitOrigHeight/(c.origWidth/c.width)-c.elementsVerticalSpacing/(c.origWidth/c.width)*b*2,10);d=parseInt(b*d.aspectOrig,
 10);a.css({height:b+"px",width:d+"px"});c.resizeImages&&(imgInside=a.find("img:first"),imgInside.is("img")&&imgInside.css({height:b+"px",width:d+"px"}))}function D(a,b,c,x,g,l,n,y,f,h,k,p,q,u,w,t){f.slideIsRunning=!0;k.html(d(p[f.current_img_no]).attr("data-title"));h.responsive&&K(k,h);0===l?a.css("z-index",f.currentZ_index-1):a.css("z-index",f.currentZ_index);a.css("display","block");a.animate({left:b+"px",top:c+"px",width:x+"px",height:g+"px",opacity:l},1E3*h.animationTime,h.easing,function(){if(n){f.slideIsRunning=
 !1;f.arcInitialTime=(new Date).getTime();f.timeElapsed=0;h.showCircleTimer&&(clearInterval(f.intervalID),f.ctx.clearRect(0,0,f.canvas.width,f.canvas.height),f.ctx.beginPath(),f.ctx.globalAlpha=h.behindCircleAlpha/100,f.ctx.arc(h.circleRadius+2*h.circleLineWidth,h.circleRadius+2*h.circleLineWidth,h.circleRadius,0,2*Math.PI,!1),f.ctx.lineWidth=h.circleLineWidth+2,f.ctx.strokeStyle=h.behindCircleColor,f.ctx.stroke(),f.ctx.beginPath(),f.ctx.globalAlpha=h.circleAlpha/100,f.ctx.arc(h.circleRadius+2*h.circleLineWidth,
 h.circleRadius+2*h.circleLineWidth,h.circleRadius,0,0,!1),f.ctx.lineWidth=h.circleLineWidth,f.ctx.strokeStyle=h.circleColor,f.ctx.stroke(),f.intervalID=setInterval(function(){I(f,h)},125),cLeftPos=d("#contentHolderUnit_"+f.current_img_no,t).css("left"),cTopPos=d("#contentHolderUnit_"+f.current_img_no,t).css("top"),d(".mycanvas",t).css({display:"block",left:parseInt(cLeftPos.substr(0,cLeftPos.lastIndexOf("px")),10)+parseInt(h.circleLeftPositionCorrection/(h.origWidth/h.width),10)+"px",top:parseInt(cTopPos.substr(0,
 cTopPos.lastIndexOf("px")),10)+parseInt(h.circleTopPositionCorrection/(h.origWidth/h.width),10)+"px"}));if(0<h.autoPlay&&1<q&&!f.mouseOverBanner&&!f.fastForwardRunning||f.current_img_no!=f.img_no_where_to_stop&&f.fastForwardRunning)clearTimeout(f.timeoutID),f.timeoutID=setTimeout(function(){B(y,h,f,w,p,t,q,u,k)},1E3*h.autoPlay);f.current_img_no==f.img_no_where_to_stop&&f.fastForwardRunning&&(f.fastForwardRunning=!1,h.animationTime=f.animationTimeOrig,h.autoPlay=f.autoPlayOrig)}});h.resizeImages&&
 (imgInside=a.find("img:first"),imgInside.is("img")&&imgInside.animate({width:x+"px",height:g+"px"},1E3*h.animationTime,h.easing,function(){}))}function F(a,b,c){return a+b>=c?0:0>a+b?c-1:a+b}function L(a,b,c,d,g,l,n,y,f){-1===c.current_img_no-a?B(1,b,c,d,g,l,n,y,f):1===c.current_img_no-a?B(-1,b,c,d,g,l,n,y,f):(c.fastForwardRunning=!0,b.animationTime=.4,b.autoPlay=.1,c.img_no_where_to_stop=a,c.current_img_no<a?a-c.current_img_no<n-a+c.current_img_no?B(1,b,c,d,g,l,n,y,f):B(-1,b,c,d,g,l,n,y,f):c.current_img_no>
 a&&(c.current_img_no-a<n-c.current_img_no+a?B(-1,b,c,d,g,l,n,y,f):B(1,b,c,d,g,l,n,y,f)))}function O(a,b,c,x,g,l,n,y,f,h,k,p,q,u,w,t,r){r=d("body").css("overflow");d("body").css("overflow","hidden");u.css("display","none");responsiveWidth=g.parent().parent().width();responsiveHeight=g.parent().parent().height();b.width100Proc&&(b.width=responsiveWidth);b.height100Proc&&(b.height=responsiveHeight);if(b.origWidth!=responsiveWidth||b.width100Proc)b.origWidth>responsiveWidth||b.width100Proc?b.width=responsiveWidth:
 b.width100Proc||(b.width=b.origWidth),b.height100Proc||(b.height=b.width/a.bannerRatio),b.width=parseInt(b.width,10),b.height=parseInt(b.height,10),n.width(b.width),n.height(b.height),t.width(b.width),t.height(b.height),l.css("margin-top",parseInt((b.height-y.height())/2+b.nextPrevMarginTop/(b.origWidth/b.width),10)+"px"),f.css("left",parseInt((n.width()-f.width())/2,10)+"px"),h.css("left",parseInt(f.css("left").substring(0,f.css("left").length-2),10)-h.width()+"px"),k.css("left",parseInt(f.css("left").substring(0,
 f.css("left").length-2),10)+f.width()+parseInt(p.css("padding-left").substring(0,p.css("padding-left").length-2),10)+"px"),u.css({left:parseInt((b.width-u.width())/2,10)+"px",top:parseInt(b.height-b.contentHolderUnitOrigHeight/(b.origWidth/b.width),10)+parseInt((b.contentHolderUnitOrigHeight/(b.origWidth/b.width)-u.height())/2-parseInt(b.verticalAdjustment/(b.origWidth/b.width),10)-b.border,10)+"px","margin-top":b.playMovieMarginTop/(b.origWidth/b.width)}),w.css("top",parseInt(b.elementOrigTop/(b.origWidth/
 b.width),10)),clearTimeout(a.timeoutID),clearInterval(a.intervalID),a.timeoutID=setTimeout(function(){B(1,b,a,q,x,n,c,u,w)},.1);d("body").css("overflow",r)}function M(a,b,c){a.effectIsRunning||G||(a.isPrettyPhoto=!1,void 0!=d(c[a.current_img_no]).attr("data-link")&&""!=d(c[a.current_img_no]).attr("data-link")?(b=b.target,void 0!=d(c[a.current_img_no]).attr("data-target")&&""!=d(c[a.current_img_no]).attr("data-target")&&(b=d(c[a.current_img_no]).attr("data-target")),"_blank"==b?window.open(d(c[a.current_img_no]).attr("data-link")):
 window.location=d(c[a.current_img_no]).attr("data-link")):void 0!=d(c[a.current_img_no]).attr("data-large-image")&&""!=d(c[a.current_img_no]).attr("data-large-image")?(a.isPrettyPhoto=!0,d.prettyPhoto.open(d(c[a.current_img_no]).attr("data-large-image"),d(c[a.current_img_no]).attr("data-title"))):void 0!=d(c[a.current_img_no]).attr("data-video-youtube")&&""!=d(c[a.current_img_no]).attr("data-video-youtube")?(a.isPrettyPhoto=!0,d.prettyPhoto.open("https://www.youtube.com/watch?v="+d(c[a.current_img_no]).attr("data-video-youtube"),
 d(c[a.current_img_no]).attr("data-title"))):void 0!=d(c[a.current_img_no]).attr("data-video-vimeo")&&""!=d(c[a.current_img_no]).attr("data-video-vimeo")?(a.isPrettyPhoto=!0,d.prettyPhoto.open("https://www.vimeo.com/"+d(c[a.current_img_no]).attr("data-video-vimeo"),d(c[a.current_img_no]).attr("data-title"))):void 0!=d(c[a.current_img_no]).attr("data-video-selfhosted")&&""!=d(c[a.current_img_no]).attr("data-video-selfhosted")?(a.isPrettyPhoto=!0,d.prettyPhoto.open(d(c[a.current_img_no]).attr("data-video-selfhosted")+
 ".mp4",d(c[a.current_img_no]).attr("data-title"))):void 0!=d(c[a.current_img_no]).attr("data-audio")&&""!=d(c[a.current_img_no]).attr("data-audio")&&(a.isPrettyPhoto=!0,d.prettyPhoto.open(d(c[a.current_img_no]).attr("data-audio")+".mp3",d(c[a.current_img_no]).attr("data-title"))));a.isPrettyPhoto&&clearTimeout(a.timeoutID)}function N(){var a=-1;"Microsoft Internet Explorer"==navigator.appName&&null!=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(navigator.userAgent)&&(a=parseFloat(RegExp.$1));return parseInt(a,
 10)}var G=!1;d.magic_carousel={version:"1.0"};d.fn.magic_carousel=function(a){a=d.extend({},d.fn.magic_carousel.defaults,a);return this.each(function(){var b=d(this);a.imageWidth-=2*a.border;a.imageHeight-=2*a.border;responsiveWidth=b.parent().width();responsiveHeight=b.parent().height();a.responsiveRelativeToBrowser&&(responsiveWidth=d(window).width(),responsiveHeight=d(window).height());a.origWidth=a.width;a.width100Proc&&(a.width=responsiveWidth);a.origHeight=a.height;a.height100Proc&&(a.height=
 responsiveHeight);a.responsive&&(a.origWidth!=responsiveWidth||a.width100Proc)&&(a.width=a.origWidth>responsiveWidth||a.width100Proc?responsiveWidth:a.origWidth,a.height100Proc||(a.height=a.width/(a.origWidth/a.origHeight)));a.width=parseInt(a.width,10);a.height=parseInt(a.height,10);var c=d("<div></div>").addClass("magic_carousel").addClass(a.skin),x=d('<div class="bannerControls">   <div class="leftNav"></div>   <div class="rightNav"></div>    </div>  <div class="contentHolder"></div>   <div class="elementTitle"></div>\t<div class="iconOver"></div>  <canvas class="mycanvas"></canvas>');
 b.wrap(c);b.after(x);var g=b.parent(".magic_carousel");x=d(".bannerControls",g);var l=d(".contentHolder",g);c=d('<div class="bottomNavLeft"></div>');var n=d('<div class="bottomNav"></div>'),y=d('<div class="bottomNavRight"></div>');b.after(c);b.after(n);b.after(y);a.showAllControllers||x.css("display","none");var f=d(".leftNav",g),h=d(".rightNav",g);f.css("display","none");h.css("display","none");a.showNavArrows&&a.showOnInitNavArrows&&(f.css("display","block"),h.css("display","block"));var k=d(".bottomNav",
 g),p=d(".bottomNavLeft",g),q=d(".bottomNavRight",g),u;k.css("display","block");p.css("display","block");q.css("display","block");k.css({bottom:a.bottomNavMarginBottom+"px",top:"auto"});p.css({bottom:a.bottomNavMarginBottom+"px",top:"auto"});q.css({bottom:a.bottomNavMarginBottom+"px",top:"auto"});a.showBottomNav||(k.css("display","none"),p.css("display","none"),q.css("display","none"));a.showOnInitBottomNav||(k.css("left","-5000px"),p.css("left","-5000px"),q.css("left","-5000px"));var w=d(".elementTitle",
 g);w.css("color",a.titleColor);a.showElementTitle||w.css("display","none");a.elementOrigTop=parseInt(w.css("top").substr(0,w.css("top").lastIndexOf("px")),10);w.css("top",parseInt(a.elementOrigTop/(a.origWidth/a.width),10));c=N();var t=d(".iconOver",g),r=0,e={current_img_no:0,currentImg:0,currentZ_index:101,slideIsRunning:!1,mouseOverBanner:!1,fastForwardRunning:!1,isPrettyPhoto:!1,img_no_where_to_stop:0,aspectOrig:0,animationTimeOrig:a.animationTime,autoPlayOrig:a.autoPlay,curIcon:"empty.png",timeoutID:"",
 intervalID:"",arcInitialTime:(new Date).getTime(),timeElapsed:0,windowWidth:0,canvas:"",ctx:"",bannerRatio:a.origWidth/a.origHeight};e.canvas=d(".mycanvas",g)[0];e.canvas.width=2*a.circleRadius+4*a.circleLineWidth;e.canvas.height=2*a.circleRadius+4*a.circleLineWidth;-1!=c&&9>c&&(a.showCircleTimer=!1);a.showCircleTimer&&(e.ctx=e.canvas.getContext("2d"));g.width(a.width);g.height(a.height);l.width(a.width);l.height(a.height);x.css("margin-top",parseInt((a.height-f.height())/2,10)+a.nextPrevMarginTop/
 (a.origWidth/a.width)+"px");a.centerPlugin&&g.css({margin:"0 auto"});var v=b.find("ul:first").children();a.numberOfVisibleItems>b.find("ul:first li").length&&(a.numberOfVisibleItems=b.find("ul:first li").length);a.numberOfVisibleItems%2||a.numberOfVisibleItems--;var C,D=0,F=0;v.each(function(){e.currentImg=d(this);e.currentImg.is("li")||(e.currentImg=e.currentImg.find("li:first"));e.currentImg.is("li")&&(r++,z=d('<div class="contentHolderUnit" rel="'+(r-1)+'" id="contentHolderUnit_'+(r-1)+'">'+e.currentImg.html()+
 "</div>"),l.append(z),z.css({display:"none",width:a.imageWidth+"px",height:a.imageHeight+"px"}),0===a.contentHolderUnitOrigWidth&&(a.contentHolderUnitOrigWidth=z.width(),a.contentHolderUnitOrigHeight=z.height(),e.aspectOrig=a.contentHolderUnitOrigWidth/a.contentHolderUnitOrigHeight),H(z,0,a,e),z.css({left:parseInt((a.width-(z.width()+2*a.border))/2,10)+"px",top:parseInt(a.height-(a.contentHolderUnitOrigHeight+2*a.border)/(a.origWidth/a.width)-a.verticalAdjustment/(a.origWidth/a.width),10)+"px","border-color":a.borderColorOFF,
 "border-width":a.border}),1==r?z.css({left:parseInt((a.width-(z.width()+2*a.border))/2,10)+"px",top:parseInt(a.height-(a.contentHolderUnitOrigHeight+2*a.border)/(a.origWidth/a.width)-a.verticalAdjustment/(a.origWidth/a.width),10)+"px","z-index":e.currentZ_index,display:"block"}):r<=Math.ceil(a.numberOfVisibleItems/2)&&(e.currentZ_index--,H(z,r-1,a,e),z.css({left:parseInt((a.width-(a.contentHolderUnitOrigWidth+2*a.border)/(a.origWidth/a.width))/2+((a.contentHolderUnitOrigWidth+2*a.border)/(a.origWidth/
 a.width)+E(r-1,a,e)-(z.width()+2*a.border)),10)+1+"px",top:parseInt(a.height-(a.contentHolderUnitOrigHeight+2*a.border)/(a.origWidth/a.width),10)-a.verticalAdjustment/(a.origWidth/a.width)+(r-1)*a.elementsVerticalSpacing/(a.origWidth/a.width)+"px","z-index":e.currentZ_index,display:"block"})),C=d('<div class="bottomNavButtonOFF" rel="'+(r-1)+'"></div>'),k.append(C),D+=parseInt(C.css("padding-left").substring(0,C.css("padding-left").length-2),10)+C.width(),F=parseInt((k.height()-parseInt(C.css("height").substring(0,
 C.css("height").length-2)))/2,10),C.css("margin-top",F+"px"))});e.curIcon="empty.png";d(v[e.current_img_no]).attr("data-link")?e.curIcon="link.png":d(v[e.current_img_no]).attr("data-large-image")?e.curIcon="image.png":d(v[e.current_img_no]).attr("data-video-youtube")||d(v[e.current_img_no]).attr("data-video-vimeo")||d(v[e.current_img_no]).attr("data-video-selfhosted")?e.curIcon="video.png":d(v[e.current_img_no]).attr("data-audio")&&(e.curIcon="audio.png");display_val="block";"empty.png"==e.curIcon&&
 (display_val="none");t.css({background:"url("+a.absUrl+"skins/"+a.skin+"/"+e.curIcon+")",left:parseInt((a.width-t.width())/2,10)+"px",top:parseInt(a.height-(a.contentHolderUnitOrigHeight+2*a.border)/(a.origWidth/a.width),10)+parseInt(((a.contentHolderUnitOrigHeight+2*a.border)/(a.origWidth/a.width)-t.height())/2,10)-parseInt(a.verticalAdjustment/(a.origWidth/a.width),10)+"px","margin-top":a.playMovieMarginTop/(a.origWidth/a.width),display:display_val});a.showCircleTimer&&(cLeftPos=d("#contentHolderUnit_"+
 e.current_img_no,g).css("left"),cTopPos=d("#contentHolderUnit_"+e.current_img_no,g).css("top"),d(".mycanvas",g).css({left:parseInt(cLeftPos.substr(0,cLeftPos.lastIndexOf("px")),10)+parseInt(a.circleLeftPositionCorrection/(a.origWidth/a.width),10)+"px",top:parseInt(cTopPos.substr(0,cTopPos.lastIndexOf("px")),10)+parseInt(a.circleTopPositionCorrection/(a.origWidth/a.width),10)+"px"}));e.currentZ_index=100;for(m=1;m<=Math.floor(a.numberOfVisibleItems/2);m++)e.currentZ_index--,H(d("#contentHolderUnit_"+
 (r-m),g),m,a,e),d("#contentHolderUnit_"+(r-m),g).css({left:parseInt((a.width-(a.contentHolderUnitOrigWidth+2*a.border)/(a.origWidth/a.width))/2-E(m,a,e),10)+"px",top:parseInt(a.height-(a.contentHolderUnitOrigHeight+2*a.border)/(a.origWidth/a.width)-a.verticalAdjustment/(a.origWidth/a.width)+m*a.elementsVerticalSpacing/(a.origWidth/a.width),10)+"px","z-index":e.currentZ_index,display:"block"});w.html(d(v[0]).attr("data-title"));a.responsive&&K(w,a);k.width(D);a.showOnInitBottomNav&&(k.css("left",parseInt((g.width()-
 D)/2,10)+"px"),p.css("left",parseInt(k.css("left").substring(0,k.css("left").length-2),10)-p.width()+"px"),q.css("left",parseInt(k.css("left").substring(0,k.css("left").length-2),10)+k.width()+parseInt(C.css("padding-left").substring(0,C.css("padding-left").length-2),10)+"px"));e.current_img_no=0;e.currentImg=d(v[e.current_img_no]);g.mouseenter(function(){e.isPrettyPhoto||(e.mouseOverBanner=!0,clearTimeout(e.timeoutID),nowx=(new Date).getTime(),e.timeElapsed+=nowx-e.arcInitialTime,a.autoHideNavArrows&&
 a.showNavArrows&&(f.css("display","block"),h.css("display","block")),a.autoHideBottomNav&&a.showBottomNav&&(k.css({display:"block",left:parseInt((g.width()-D)/2,10)+"px"}),p.css({display:"block",left:parseInt(k.css("left").substring(0,k.css("left").length-2),10)-p.width()+"px"}),q.css({display:"block",left:parseInt(k.css("left").substring(0,k.css("left").length-2),10)+k.width()+parseInt(C.css("padding-left").substring(0,C.css("padding-left").length-2),10)+"px"})))});g.mouseleave(function(){if(!e.isPrettyPhoto&&
 (e.mouseOverBanner=!1,nowx=(new Date).getTime(),a.autoHideNavArrows&&a.showNavArrows&&(f.css("display","none"),h.css("display","none")),a.autoHideBottomNav&&a.showBottomNav&&(k.css("display","none"),p.css("display","none"),q.css("display","none")),0<a.autoPlay&&1<r&&!e.fastForwardRunning&&!e.isPrettyPhoto)){clearTimeout(e.timeoutID);e.arcInitialTime=(new Date).getTime();var b=parseInt(1E3*a.autoPlay-(e.timeElapsed+nowx-e.arcInitialTime),10);e.timeoutID=setTimeout(function(){B(1,a,e,A,v,g,r,t,w)},
 b)}});d.magic_carousel.continueAutoplay=function(a){e.isPrettyPhoto=!1;g.mouseleave()};var z=d(".contentHolderUnit",g);z.mouseover(function(){d(this).attr("rel")==e.current_img_no&&t.css("display","block");d(this).css({"border-color":a.borderColorON})});z.mouseout(function(){d(this).attr("rel")==e.current_img_no&&t.css("display","none");d(this).css({"border-color":a.borderColorOFF})});z.click(function(){if(!e.slideIsRunning&&!e.fastForwardRunning){var b=d(this).attr("rel");b!=e.current_img_no?(d(A[e.current_img_no]).removeClass("bottomNavButtonON"),
 L(parseInt(b,10),a,e,A,v,g,r,t,w)):M(e,a,v)}});t.mouseover(function(){t.css("display","block")});t.click(function(){M(e,a,v)});f.mousedown(function(){G=!0;e.slideIsRunning||e.fastForwardRunning||(e.isPrettyPhoto=!1,clearTimeout(e.timeoutID),B(-1,a,e,A,v,g,r,t,w))});f.mouseup(function(){G=!1});h.mousedown(function(){G=!0;e.slideIsRunning||e.fastForwardRunning||(e.isPrettyPhoto=!1,clearTimeout(e.timeoutID),B(1,a,e,A,v,g,r,t,w))});h.mouseup(function(){G=!1});var A=d(".bottomNavButtonOFF",g);A.mousedown(function(){G=
 !0;if(!e.slideIsRunning&&!e.fastForwardRunning){var b=d(this).attr("rel");b!=e.current_img_no&&(e.isPrettyPhoto=!1,d(A[e.current_img_no]).removeClass("bottomNavButtonON"),a.showPreviewThumbs&&u.remove(),L(parseInt(b,10),a,e,A,v,g,r,t,w))}});A.mouseup(function(){G=!1});A.mouseenter(function(){var b=d(this),c=b.attr("rel");a.showPreviewThumbs&&(u=d('<div class="bottomOverThumb"></div>'),b.append(u),c=d(v[c]).attr("data-bottom-thumb"),u.html('<img src="'+c+'">'));b.addClass("bottomNavButtonON")});A.mouseleave(function(){var b=
 d(this),c=b.attr("rel");a.showPreviewThumbs&&u.remove();e.current_img_no!=c&&b.removeClass("bottomNavButtonON")});a.enableTouchScreen&&g.swipe({swipe:function(b,c,d,f,h){e.effectIsRunning||B("right"==c?-1:1,a,e,A,v,g,r,t,w)}});var J=!1;d(window).resize(function(){var c=String(navigator.userAgent).toLowerCase();if(!e.isPrettyPhoto||"undefined"==String(d(v[e.current_img_no]).attr("data-video-selfhosted"))||-1!=c.indexOf("android")||-1!=c.indexOf("ipad")||-1!=c.indexOf("iphone")||-1!=c.indexOf("ipod")||
 -1!=c.indexOf("webos")){var h=N();doResizeNow=!0;-1!=h&&9==h&&0==e.windowWidth&&(doResizeNow=!1);e.windowWidth==d(window).width()?(doResizeNow=!1,a.windowCurOrientation==window.orientation||-1==c.indexOf("android")&&-1==c.indexOf("ipad")&&-1==c.indexOf("iphone")&&-1==c.indexOf("ipod")&&-1==c.indexOf("webos")||(a.windowCurOrientation=window.orientation,doResizeNow=!0)):e.windowWidth=d(window).width();a.responsive&&doResizeNow?(!1!==J&&clearTimeout(J),e.isPrettyPhoto&&d.prettyPhoto.close(),J=setTimeout(function(){O(e,
 a,r,v,b,x,g,f,k,p,q,C,A,t,w,l,z)},300)):doResizeNow&&e.isPrettyPhoto&&d.prettyPhoto.close()}});d(A[e.current_img_no]).addClass("bottomNavButtonON");c=g.find("img:first");c[0].complete?(d(".myloader",g).css("display","none"),0<a.autoPlay&&1<r&&(a.showCircleTimer&&(e.arcInitialTime=(new Date).getTime(),e.timeElapsed=0,e.intervalID=setInterval(function(){I(e,a)},125)),e.timeoutID=setTimeout(function(){B(1,a,e,A,v,g,r,t,w)},1E3*a.autoPlay))):c.load(function(){d(".myloader",g).css("display","none");0<
 a.autoPlay&&1<r&&(a.showCircleTimer&&(e.arcInitialTime=(new Date).getTime(),e.timeElapsed=0,e.intervalID=setInterval(function(){I(e,a)},125)),e.timeoutID=setTimeout(function(){B(1,a,e,A,v,g,r,t,w)},1E3*a.autoPlay))})})};d.fn.magic_carousel.defaults={skin:"white",width:960,height:384,width100Proc:!1,height100Proc:!1,autoPlay:4,numberOfVisibleItems:3,elementsHorizontalSpacing:120,elementsVerticalSpacing:20,verticalAdjustment:0,animationTime:.8,easing:"easeOutQuad",resizeImages:!0,target:"_blank",showElementTitle:!0,
 showAllControllers:!0,showNavArrows:!0,showOnInitNavArrows:!0,autoHideNavArrows:!0,showBottomNav:!0,showOnInitBottomNav:!0,autoHideBottomNav:!0,showPreviewThumbs:!0,nextPrevMarginTop:0,playMovieMarginTop:0,enableTouchScreen:!0,absUrl:"",titleColor:"#000000",imageWidth:452,imageHeight:302,border:0,borderColorOFF:"transparent",borderColorON:"#FF0000",showCircleTimer:!0,showCircleTimerIE8IE7:!1,circleRadius:10,circleLineWidth:4,circleColor:"#FF0000",circleAlpha:100,behindCircleColor:"#000000",behindCircleAlpha:50,
 circleLeftPositionCorrection:3,circleTopPositionCorrection:3,responsive:!0,responsiveRelativeToBrowser:!1,centerPlugin:!1,bottomNavMarginBottom:0,origWidth:0,origHeight:0,contentHolderUnitOrigWidth:0,contentHolderUnitOrigHeight:0,elementOrigTop:0,origthumbsHolder_MarginTop:0,windowOrientationScreenSize0:0,windowOrientationScreenSize90:0,windowOrientationScreenSize_90:0,windowCurOrientation:0}})(jQuery);